version: "3.7"

services:
  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pm_dev
  redis:
    image: redis:latest
    container_name: pm_redis
    ports:
      - "6382:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"

volumes:
  postgres_data:
