# Generated by Django 3.2.7 on 2021-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
