# Generated by Django 3.2.7 on 2021-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_fileitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='processing_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
